import { Card, CardContent } from '@/components/ui/card';
import { Sparkles, ShieldAlert } from 'lucide-react';

export function AISummaryCard({ data }: { data?: string }) {
  if (!data) return null;

  return (
    <Card className="border-indigo-500/30 bg-gradient-to-r from-indigo-950/20 to-purple-950/20 relative overflow-hidden">
      <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
        <Sparkles className="w-24 h-24 text-indigo-400" />
      </div>
      <CardContent className="p-6 relative z-10 flex flex-col gap-4">
        <div className="flex items-start gap-4">
          <div className="p-2.5 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex-shrink-0 mt-1">
            <Sparkles className="w-5 h-5 text-indigo-400" />
          </div>
          <div>
            <h4 className="text-body font-bold text-indigo-300 mb-1.5 uppercase tracking-wider text-xs">Executive Summary</h4>
            <p className="text-[15px] leading-relaxed text-foreground/90 font-medium">{data}</p>
          </div>
        </div>
        <div className="flex items-start gap-2 p-3 rounded-lg bg-white/3 border border-white/5">
          <ShieldAlert className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0 mt-0.5" />
          <p className="text-[11px] text-muted-foreground/60 leading-relaxed">
            This analysis is generated by AI and is for informational purposes only. It does not constitute investment advice. 
            Consult a SEBI-registered investment advisor before making financial decisions.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
